apiVersion: v1
kind: Pod
metadata:
  name: "mydb3"
  labels:
    app: mydb2
spec:
  containers:
    - name:  "mydb2"
      image: "mysql:5.7"
      env:
       - name: MYSQL_ROOT_PASSWORD
         valueFrom:
            secretKeyRef:
              name: mysecret
              key: p
       - name: MYSQL_USER
         value: ayush
       - name: MYSQL_PASSWORD
         value: redhat

